"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import {
  FileText,
  ChevronDown,
  Filter,
  DollarSign,
  Clock,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Send,
} from "lucide-react";

interface Report {
  id: string;
  exploit_id: string;
  programme_id: string;
  title: string;
  severity: string;
  cvss_score: number;
  report_markdown: string;
  status: string;
  submitted_at: string | null;
  resolved_at: string | null;
  bounty_amount: number | null;
  created_at: string;
  programme_name: string;
}

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterStatus, setFilterStatus] = useState("");

  async function loadReports() {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (filterStatus) params.set("status", filterStatus);
      const res = await fetch(`/api/reports?${params.toString()}`);
      const data = await res.json();
      if (data.reports) setReports(data.reports);
    } catch (err) {
      console.error("Failed to load reports", err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadReports();
  }, [filterStatus]);

  async function updateStatus(id: string, newStatus: string) {
    try {
      await fetch("/api/reports", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, status: newStatus }),
      });
      loadReports();
    } catch (err) {
      console.error("Failed to update status", err);
    }
  }

  const severityColor = (sev: string) => {
    const colors: Record<string, string> = {
      critical: "bg-rose-500/20 text-rose-400 border-rose-500/30",
      high: "bg-purple-500/20 text-purple-400 border-purple-500/30",
      medium: "bg-amber-500/20 text-amber-400 border-amber-500/30",
      low: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
      info: "bg-slate-500/20 text-slate-300 border-slate-500/30",
    };
    return colors[sev?.toLowerCase()] || colors.info;
  };

  const statusIcon = (status: string) => {
    switch (status) {
      case "accepted":
        return <CheckCircle2 className="w-4 h-4 text-emerald-400" />;
      case "rejected":
        return <XCircle className="w-4 h-4 text-rose-400" />;
      case "submitted":
        return <Send className="w-4 h-4 text-blue-400" />;
      case "informative":
        return <AlertTriangle className="w-4 h-4 text-amber-400" />;
      default:
        return <Clock className="w-4 h-4 text-slate-400" />;
    }
  };

  const statusColor = (status: string) => {
    const colors: Record<string, string> = {
      draft: "bg-slate-500/20 text-slate-300 border-slate-500/30",
      submitted: "bg-blue-500/20 text-blue-400 border-blue-500/30",
      accepted: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
      rejected: "bg-rose-500/20 text-rose-400 border-rose-500/30",
      informative: "bg-amber-500/20 text-amber-400 border-amber-500/30",
    };
    return colors[status] || colors.draft;
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <header>
        <h2 className="text-3xl font-bold tracking-tight text-white">
          Reports
        </h2>
        <p className="text-slate-400 mt-1">
          Bug reports generated by the report agent
        </p>
      </header>

      {/* Filter */}
      <div className="flex gap-4">
        <div className="relative">
          <Filter className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <select
            value={filterStatus}
            onChange={(e) => setFilterStatus(e.target.value)}
            className="bg-[rgba(30,41,59,0.5)] border border-[var(--color-panel-border)] rounded-xl pl-9 pr-8 py-2.5 text-sm text-white focus:outline-none focus:border-cyan-500 appearance-none min-w-[160px]"
          >
            <option value="">All Statuses</option>
            <option value="draft">Draft</option>
            <option value="submitted">Submitted</option>
            <option value="accepted">Accepted</option>
            <option value="rejected">Rejected</option>
            <option value="informative">Informative</option>
          </select>
          <ChevronDown className="w-4 h-4 absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
        </div>
      </div>

      {/* Reports Grid */}
      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {[1, 2, 3, 4].map((i) => (
            <div key={i} className="glass-panel p-6 animate-pulse space-y-4">
              <div className="h-5 w-48 bg-slate-700/50 rounded" />
              <div className="h-3 w-24 bg-slate-700/50 rounded" />
              <div className="h-20 bg-slate-700/50 rounded" />
            </div>
          ))}
        </div>
      ) : reports.length === 0 ? (
        <div className="glass-panel p-16 text-center">
          <FileText className="w-16 h-16 text-slate-600 mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-white mb-2">
            No reports yet
          </h3>
          <p className="text-slate-400">
            Reports will appear here once exploits are confirmed and documented
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {reports.map((r, i) => (
            <motion.div
              key={r.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              className="glass-panel p-6 space-y-4 hover:border-cyan-500/20 transition-all"
            >
              {/* Title & Severity */}
              <div className="flex justify-between items-start gap-3">
                <h3 className="text-white font-semibold text-lg leading-tight flex-1">
                  {r.title || "Untitled Report"}
                </h3>
                {r.severity && (
                  <span className={`px-2.5 py-1 rounded-full text-xs font-semibold border uppercase shrink-0 ${severityColor(r.severity)}`}>
                    {r.severity}
                  </span>
                )}
              </div>

              {/* Meta Row */}
              <div className="flex flex-wrap gap-4 text-sm">
                <span className="text-slate-400">{r.programme_name}</span>
                {r.cvss_score !== null && (
                  <span className="text-white font-medium">
                    CVSS {r.cvss_score.toFixed(1)}
                  </span>
                )}
                {r.bounty_amount !== null && r.bounty_amount > 0 && (
                  <span className="text-emerald-400 font-medium flex items-center gap-1">
                    <DollarSign className="w-3.5 h-3.5" />
                    {Number(r.bounty_amount).toLocaleString()}
                  </span>
                )}
              </div>

              {/* Markdown Preview */}
              {r.report_markdown && (
                <div className="p-4 bg-[rgba(15,23,42,0.6)] rounded-lg text-xs text-slate-300 font-mono max-h-32 overflow-y-auto whitespace-pre-wrap">
                  {r.report_markdown.substring(0, 500)}
                  {r.report_markdown.length > 500 && "..."}
                </div>
              )}

              {/* Status + Actions */}
              <div className="flex justify-between items-center pt-4 border-t border-[var(--color-panel-border)]">
                <div className="flex items-center gap-2">
                  {statusIcon(r.status)}
                  <span className={`px-2.5 py-1 rounded-full text-xs font-medium border ${statusColor(r.status)}`}>
                    {r.status}
                  </span>
                </div>

                <div className="relative">
                  <select
                    value={r.status}
                    onChange={(e) => updateStatus(r.id, e.target.value)}
                    className="bg-[rgba(30,41,59,0.5)] border border-[var(--color-panel-border)] rounded-lg px-3 pr-7 py-1.5 text-xs text-white focus:outline-none focus:border-cyan-500 appearance-none"
                  >
                    <option value="draft">Draft</option>
                    <option value="submitted">Submitted</option>
                    <option value="accepted">Accepted</option>
                    <option value="rejected">Rejected</option>
                    <option value="informative">Informative</option>
                  </select>
                  <ChevronDown className="w-3 h-3 absolute right-2 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
